language: go

go:
  - 1.8.x

addons:
  artifacts:
    paths:
      - ./joltron-linux
      - ./joltron-mac
      - ./joltron.exe

before_install:
  - go get github.com/campoy/jsonenums

script:
  - CGO_ENABLED=0 GOOS=linux GOARCH=386 sh ./build.sh
  - mv ./joltron ./joltron-linux
  - CGO_ENABLED=0 GOOS=darwin GOARCH=386 sh ./build.sh
  - mv ./joltron ./joltron-mac
  - CGO_ENABLED=0 GOOS=windows GOARCH=386 sh ./build.sh
  - ls -lah
