version: 2
jobs:
  build:
    working_directory: /go/src/github.com/gamejolt/joltron
    docker:
      - image: circleci/golang:1.8.3
    steps:
      - checkout
      - run: go get github.com/campoy/jsonenums
      - run: go get -v ./...
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=386 sh ./build.sh
      - run: mv ./joltron ./joltron_linux
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=386 sh ./build.sh
      - run: mv ./joltron ./joltron_osx
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=386 sh ./build.sh
      - run: mv ./joltron.exe ./joltron_win32.exe
      - run: ls -lah
      - store_artifacts:
          path: "joltron_linux"
      - store_artifacts:
          path: "joltron_osx"
      - store_artifacts:
          path: "joltron_win32.exe"
